# fly.toml app configuration file generated for simple-sso-server on 2024-08-08T20:37:18+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simple-sso-server'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
